---
- name: BIG-IP SETUP
  hosts: ip-10-0-0-78.us-west-1.compute.internal
  connection: local
  gather_facts: false
  vars_files: web_app.yml

  tasks:
    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{ansible_host}}"
        server_port: "443"
        validate_certs: "False"

    - name: ADD iRules
      bigip_irule:
        provider: "{{provider}}"
        module: "ltm"
        name: "irule1"
        content: "{{lookup('file','irule1')}}"

    - name: ATTACH iRules TO VIRTUAL SERVER
      bigip_virtual_server:
        provider: "{{provider}}"
        name: "{{ website }}_{{ vip_port }}_VS"
        irules: "irule1"
        destination: "{{ vip }}"
        port: "{{ vip_port}}"
