---
- name: BIG-IP SETUP
  hosts: ltm
  connection: local
  gather_facts: false
  vars_files: web_app.yml

  tasks:

    - name: Add HA VLAN(s) on BIG-IP1
      bigip_vlan:
        provider:
           server: "{{bigip1_ip}}"
           validate_certs: "False"
        name: "{{item.name}}"
        tag: "{{item.id}}"
        tagged_interfaces:
        - "{{item.interface}}"
      with_items: "{{ha_vlan_information}}"

    - name: Add HA VLAN(s) on BIG-IP2
      bigip_vlan:
        provider:
           server: "{{bigip2_ip}}"
           validate_certs: "False"
        name: "{{item.name}}"
        tag: "{{item.id}}"
        tagged_interfaces:
        - "{{item.interface}}"
      with_items: "{{ha_vlan_information}}"

    - name: Add HA SELF-IP(s) on BIG-IP1
      bigip_selfip:
       provider:
          server: "{{bigip1_ip}}"
          validate_certs: "False"
       name: "{{item.name}}"
       address: "{{item.address}}"
       netmask: "{{item.netmask}}"
       vlan: "{{item.vlan}}"
      with_items: "{{ bigip1_ha_selfip }}"

    - name: Add HA SELF-IP(s) on BIG-IP2
      bigip_selfip:
       provider:
          server: "{{bigip1_ip}}"
          validate_certs: "False"
       name: "{{item.name}}"
       address: "{{item.address}}"
       netmask: "{{item.netmask}}"
       vlan: "{{item.vlan}}"
      with_items: "{{ bigip2_ha_selfip }}"

    - name: Config Sync/unicast/mirroring address - BIGIP1
      bigip_device_connectivity:
        provider:
          server: "{{bigip1_ip}}"
          validate_certs: "False"
        config_sync_ip: "{{bigip1_ha_selfip[0]['address']}}"
        mirror_primary_address: "{{bigip1_ha_selfip[0]['address']}}"
        unicast_failover:
        - address: "{{bigip1_ha_selfip[0]['address']}}"
        - address: "{{bigip1_ip}}"
      delegate_to: localhost

    - name: Config Sync/unicast/mirroring address - BIGIP2
      bigip_device_connectivity:
        provider:
          server: "{{bigip2_ip}}"
          validate_certs: "False"
        config_sync_ip: "{{bigip2_ha_selfip[0]['address']}}"
        mirror_primary_address: "{{bigip2_ha_selfip[0]['address']}}"
        unicast_failover:
        - address: "{{bigip2_ha_selfip[0]['address']}}"
        - address: "{{bigip2_ip}}"
      delegate_to: localhost

    - name: Device trust
      bigip_device_trust:
        provider:
          server: "{{bigip1_ip}}"
          validate_certs: "False"
        peer_server: "{{ bigip2_ip }}"
        peer_hostname: "{{ bigip2_hostname }}"
        peer_user: "{{ bigip2_username }}"
        peer_password: "{{ bigip2_password }}"
      delegate_to: localhost

    - name: Add Device Group
      bigip_device_group:
        provider:
          server: "{{bigip1_ip}}"
          validate_certs: "False"
        name: "deviceGrp"
        auto_sync: yes
        type: "sync-failover"
      delegate_to: localhost
   
    - name: Add members to the device group
      bigip_device_group_member:
        provider:
          server: "{{bigip1_ip}}"
          validate_certs: "False"
        device_group: "deviceGrp"
        name: "{{ item }}"
      with_items:
        - "{{bigip1_hostname}}"
        - "{{bigip2_hostname}}"
      delegate_to: localhost
   
    - name: Perform a config sync
      bigip_configsync_action:
        provider:
          server: "{{bigip1_ip}}"
          validate_certs: "False"
        device_group: "deviceGrp"
        sync_device_to_group: yes
      delegate_to: localhost