---
- name: BIG-IP SETUP
  hosts: ltm01
  connection: local
  gather_facts: false
  vars_files: web_app.yml
  
  tasks:
    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{ansible_host}}"
        server_port: "443"
        validate_certs: "False"
  
    - name: CREATE NODES
      bigip_node:
       address: "{{ item.ip }}"
       name: "{{ item.name }}"
       provider: "{{ provider }}"
       monitors:
          - my_http_monitor
       state: present
      loop: "{{ pool_members }}"


  