---
- name: BIG-IP SETUP
  hosts: ltm01
  connection: local
  gather_facts: false
  vars_files: web_app.yml
  
  tasks:
    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{ansible_host}}"
        server_port: "443"
        validate_certs: "False"
  
    - name: DELETE POOL
      bigip_pool:
        provider: "{{provider}}"
        name: "http_pool"
        state: absent
  
    - name: DELETE NODES
      bigip_node:
        provider: "{{provider}}"
        name: "{{ item.name }}"
        state: absent
      loop: "{{ pool_members }}"