---
- name: BIG-IP SETUP
  hosts: ip-10-0-0-78.us-west-1.compute.internal
  connection: local
  gather_facts: false
  vars_files: web_app.yml

  tasks:
    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{ ansible_host }}"
        server_port: "443"
        validate_certs: "False"
  
    - name: DELETE VIRTUAL SERVER
      bigip_virtual_server:
        provider: "{{provider}}"
        name: "{{ website }}_{{ vip_port }}_VS"
        state: absent
  
    - name: DELETE POOL
      bigip_pool:
        provider: "{{provider}}"
        name: "POOL_{{ website }}_{{ vip_port }}"
        state: absent
  
    - name: DELETE NODES
      bigip_node:
        provider: "{{provider}}"
        name: "{{ item.name }}"
        state: absent
      loop: "{{ pool_members }}"