---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{private_ip}}"
        server_port: "8443"
        validate_certs: "False"

    - name: DETACH iRules TO VIRTUAL SERVER
      bigip_virtual_server:
        provider: "{{provider}}"
        name: "vip"
        irules: ""

    - name: DELETE iRules
      bigip_irule:
        provider: "{{provider}}"
        module: "ltm"
        name: "irule1"
        state: absent
